name: etc mage build pipeline

on:
  push:
    branches:
      - master

jobs:
  CryptoImageBuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'https://github.com/etclabscore/core-geth.git'