name: geth classic image build pipeline

on:
  push:
    branches:
      - master

jobs:
  CryptoImageBuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "etclabscore/core-geth"

      - name: container registry login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jithin-zachariah
          password: ${{ secrets.GHCR_TOKEN }}

      - name: docker build latest
        run: |
          docker build --build-arg GPR_TOKEN -t $DOCKER_REGISTRY/jithin-zachariah/geth-classic:latest .
        env:
          GPR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          DOCKER_REGISTRY: ghcr.io

      - name: docker push latest
        run: |
          docker push $DOCKER_REGISTRY/jithin-zachariah/geth-classic:latest
        env:
          DOCKER_REGISTRY: ghcr.io